### ISSUE TITLE
Version 0.7 (Core Functionality) Task List

### ISSUE THREAD

**Issue by nickgermaine** [nickgermaine/vinyl-music#5]
- [ ] Album Tile View
- [ ] Get Artist Images (Scrape from the web?  Maybe write a c++ integration that can search artist on wikipedia or other cc site, and grab image?)
- [ ] Multi-threading where possible/logical
- [ ] Completely debug previous track button
- [ ] Make sidebar buttons refresh current view when clicking the current sidebar item
